### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/prettier-eslint_d#1]
Dumping a todo list here:

- [ ] `--eslint-config-path` support
- [ ] Support for [w0rp/ale](https://github.com/w0rp/ale)
- [ ] Instructions for (neo)vim
